# nginx config

server {
    listen 127.0.0.1:8000;
    root /home/karaoke-videoplayer/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location ~* \.(svg|png|jpg|gif|ico|woff2?|ttf)$ {
        expires 30d;
    }
}
